spring:
  application:
    name: OrarUBB-Backend 

  datasource:
    url: jdbc:postgresql://localhost:9876/postgres
    username: postgres
    password: untested-hate-club 
  
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    jmx:
      exposure:
        include: '*'

server:
  address: 0.0.0.0
  port: 8080
