spring:
  application:
    name: OrarUBB-Backend 

  datasource:
    url: jdbc:postgresql://localhost:5432/orarubb
    username: postgres
    password: 'robi*4526'
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    jmx:
      exposure:
        include: '*'