spring:
  application:
    name: OrarUBB-Backend 

  datasource:
    url: jdbc:postgresql://localhost:9876/postgres
    username: postgres
    password: '*****'
  
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
