spring:
  application:
    name: OrarUBB-Backend 

  config:
    import: application-secrets.yml
  main:
    lazy-initialization: true
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    jmx:
      exposure:
        include: '*'

server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native
  servlet:
    context-path: /apps/orar/api
